### ISSUE TITLE
Provide a compiled version.

### ISSUE THREAD

**Issue by satoshinakamotos** [keybase/warpwallet#21]
Would be great to have a pre-compiled version here aswell as I don't have all the necessary tools here to compile it. I rather download warpwallet from github vs the website.

**Comment by maxtaco** [comment]
the website is self-contained, it should work to just click save.  no external includes, etc.

**Comment by duckx** [comment]
wow tat was fast. :) ... i'm trying to compile it from your instructions: 

$ npm install -g iced-coffee-script

But i'm getting: http://prntscr.com/9wz337

**Comment by maxtaco** [comment]
your version of node is truly ancient
