### ISSUE TITLE
404?

### ISSUE THREAD

**Issue by knocte** [keybase/warpwallet#42]
Hey keybase/warpwallet devs,

I see these days when you google for "warpwallet" the first result is still a URL that actually more often than not yields in a 404 nginx error.

I have always been a big fan of this project myself, even though I never liked the way it was used and "deployed". That's why I replicated a similar idea myself, but with a mobile/desktop app instead of a web app: https://gitlab.gnome.org/World/geewallet/blob/frontend/ReadMe.md#geewallet

Maybe you guys are interested to redirect to this project instead of returning a 404? Or just host an informative page where you state the reason of why you can't maintain it anymore, and suggest geewallet instead.

Let me know if you have any questions. Thanks

**Comment by maxtaco** [comment]
Sorry, it's fixed now.
